version: 0.0
os: linux

files:
  - source: /
    destination: /srv/kickon/prod

permissions:
  - object: /srv/kickon/prod/scripts
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: ubuntu

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu