version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/springboot-dev  # EC2의 애플리케이션 배포 경로

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: ubuntu

  AfterInstall:
  # 필요하면 DB 마이그레이션, 권한 설정 등
  # start.sh는 여기서 실행하지 않음

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: ubuntu
