version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/springboot-dev  # EC2의 애플리케이션 배포 경로

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: ubuntu

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
