version: 0.0
os: linux

files:
  - source: /
    destination: /srv/kickon/dev

# 실행 권한 자동 부여 (dev 경로 기준)
permissions:
  - object: /srv/kickon/dev/scripts
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: ubuntu

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu